sonar.projectKey=patientsync-backend
sonar.projectName=patientsync-backend
sonar.projectVersion=1.0

sonar.sources=app/dhapp/backend
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.js,**/*.spec.js,**/coverage/**

sonar.javascript.lcov.reportPaths=app/dhapp/backend/api/coverage/lcov.info

sonar.sourceEncoding=UTF-8
