services:
  backend-api:
    image: dhapp/backend-api:${IMAGE_TAG:-local}
    build:
      context: ./api
      dockerfile: Dockerfile

  billing-api:
    image: dhapp/billing-api:${IMAGE_TAG:-local}
    build:
      context: ./billing-service
      dockerfile: Dockerfile

  ai-service:
    image: dhapp/ai-service:${IMAGE_TAG:-local}
    build:
      context: ./ai-service
      dockerfile: Dockerfile

  login-gateway:
    image: dhapp/login-gateway:${IMAGE_TAG:-local}
    build:
      context: ./login-gateway
      dockerfile: Dockerfile
